### PR TITLE
Add continuous integration.

### PR DESCRIPTION
**Pull request by fracting**
Dear mintty developers,

I'd like to volunteer to maintain a continuous integration for mintty project, here is a demo: https://tea-ci.org/fracting/mintty/26

I'll raise a discussion in cygwin mailing list and reference this pull request.

Thanks!

### CODE REVIEW

**Comment by mintty** [comment]
Your offer and volunteering proposal is appreciated but the benefit is still unclear.
CI is a good thing in a professional environment and especially for server software or business functions. Both is not the case here. Concerns are:
- It might raise effort for maintaining mintty.
- Automatic testing is hard for interactive programs. Your log file issue was quite special, and if anything like that occurs, it will be easy to revert to the previous version until a fix comes soon (mostly). What about actual terminal features, how would you test them?
- It might encourage people further to submit unsolicited pull requests which in turn create additional maintenance effort; see the general remark about this on the homepage.

**Comment by fracting** [comment]
> It might raise effort for maintaining mintty.

I won't argue whether it will raise effort or reduce effort since I'm not the maintainer. I appreciate all the effort you did, and I want to help on maintaining, at least the CI part ;) Actually I can think of some case that could be helpful to save your time as well. For example, once our CI environment supports both 32bit and 64bit, then this kind of 64bit build failures could be easy detected at the first minute: https://github.com/mintty/mintty/issues/527#issuecomment-199007322

> CI is a good thing in a professional environment and especially for server software or business functions. Both is not the case here.

We've already use Mintty in the Tea CI server, so Mintty becomes "server software" for us now, that's why I propose to maintain the CI solution for Mintty itself, which is part of the process of bootstrapping the CI server. 

> Your log file issue was quite special, and if anything like that occurs, it will be easy to revert to the previous version until a fix comes soon (mostly). 

Mintty is the critical part of Tea CI server, if Mintty breaks, then all other users using Tea CI server will be affected, so we hope to make sure Mintty always works fine, and if there is anything wrong, we hope to catch bug before formal stable Mintty release rather than after Mintty release, other wise it  would be too late.

> What about actual terminal features, how would you test them?
To be honest, for the usage of Tea CI server, only those non-interactive features are critical enough for me. I did think about test cases for interactive features, but there is no good way yet, and I agree that even if we implement some test case for interactive features using tools like autohotkey, the maintainer cost might be expensive, so I skipped this part at least for the first try.

> It might encourage people further to submit unsolicited pull requests which in turn create additional maintenance effort; see the general remark about this on the homepage.
I don't know how many unsolicited pull requests there were, I also can't image CI server could encourage unsolicited pull requests, but I can add some printing of "Don't submit unsolicited pull requests" in every CI build log to make you happier ;) Well, that's just a joke. Serious speaking, I just have no idea on this point, I don't agree but also don't disagree.

Thank you for the quick response and the great work!

**Comment by fracting** [comment]
Hello,

When building latest mintty, I got an error as below:
```
minibidi.c: In function ‘bidi_class’:
minibidi.c:179:25: fatal error: bidiclasses.t: No such file or directory
compilation terminated.
```

See https://tea-ci.org/fracting/mintty/29

Would you mind help me understanding if I miss anything?

Thanks!

**Comment by mintty** [comment]
A new include file had not yet been committed; fixed meanwhile.

**Comment by fracting** [comment]
Thanks for the response. But it seems still doesn't work for me, there is no bidiclasses.t in the repository. If I try `cd src && make bidiclasses.t`, then I get an error of ` etc/UnicodeData.txt：No such file or directory`.

Did I miss anything? Or is the mintty github repository out of sync?

Thanks!

**Comment by mintty** [comment]
The file is now included in the ZIP download although for some reason it does not yet show up in the repository web interface.
Also enhance makefiles to automatically download the Unicode source file.

**Comment by fracting** [comment]
Right, github is broken today, let's see how soon they will fix it...

**Comment by fracting** [comment]
It builds now, thanks @mintty!
https://tea-ci.org/fracting/mintty/34

(The github broken seems not fixed yet: https://status.github.com/messages)

**Comment by mintty** [comment]
Clearing up open requests, I'll close this one as I still don't see the value-add and I don't wish to maintain 3rd-party items (such as test cases) in this repository. Thanks anyway.

**Comment by mintty** [comment]
Is this still an offer?
As mentioned in #1142, it might help to get a certificate that could improve installation of packages like wsltty or others that embed mintty. Integration would need to be with appveyor to this aim.

**Comment by fracting** [comment]
> Is this still an offer? As mentioned in #1142, it might help to get a certificate that could improve installation of packages like wsltty or others that embed mintty. Integration would need to be with appveyor to this aim.

Dear team, sorry I've stopped the Tea CI project for a few years. I think appveyor is the right approach. Unfortunately I'm not working in these area anymore, I wish someone else can contribute to appveyor CI. Cheers!

**Comment by Biswa96** [comment]
wsltty uses Appveyor CI. I can try. So, what's the plan? What are the steps CI should run?

**Comment by mintty** [comment]
I've obtained an Appveyor account, imported a mintty repository (a test clone, actually), and started Build, with the following error response:
```
Build started
git clone -q --branch=master https://github.com/mined/mintty.ci.git C:\projects\mintty-ci
git checkout -qf f1f6[2](https://ci.appveyor.com/project/mined/mintty-ci#L2)ddea0f16780[3](https://ci.appveyor.com/project/mined/mintty-ci#L3)0e9183[4](https://ci.appveyor.com/project/mined/mintty-ci#L4)16e6a8bac0c687c7
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```
which is not really suprising - how should I tell them to use cygwin as a build environment in the first place and what other configuration is needed?
I took a look at these resources:
https://github.com/vim/vim/blob/master/.appveyor.yml
https://github.com/mintty/mintty/commit/1041d3e37e6de4cece897b21bf5dd21e33fcb03f
but somehow this appears as a puzzle...

**Comment by Biswa96** [comment]
So, you just want to build mintty? Any artifacts to be uploaded or run tests etc.?

**Comment by mintty** [comment]
Just a build. Maybe a dummy test like in the second reference above, just for demonstration how testing could be integrated.

**Comment by mintty** [comment]
See #1149.

**Pull request closed without merging**
