### PR TITLE
add dark mode support partially (mintty/wsltty#157)

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by mintty** [comment]
Thanks a lot. Uploaded minor tweak and changelog.

**Comment by BrianInglis** [comment]
How does this interoperate in Windows "Night Light" mode?

**Comment by Biswa96** [comment]
Does that mode change anything to Command Prompt?What do you want to look mintty to be in night mode? AFAIK, the night mode is a UWP thingy.

**Comment by BrianInglis** [comment]
On my monitor, everything including the background wallpaper and windows look like reddish-yellowy faded paper.

**Comment by mintty** [comment]
What is night light mode (I remember something like it back in Windows XP...); how do I set it up for testing?
How does mintty currently look in this mode and why is it not satisfying?
And how many other specialties will there be that could be considered...?

**Comment by BrianInglis** [comment]
Win10/Settings (Action Centre)/Night Light icon. 
Appearance is currently okay. 
Should also be tested with dark mode.

**Comment by Biswa96** [comment]
The undocumented function `ShouldAppsUseDarkMode()` uses `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize\SystemUsesLightTheme` registry. So, it **may be** replaced with `RegGetValueW()` to query that REG_DWORD value.

**Pull request merged**
