### PR TITLE
Add initial support for SIXEL graphics feature(DECSIXEL, #571, #572)

### PR DESCRIPTION
**Pull request by saitoha**
This patch adds SIXEL graphics feature to mintty (related: #572, #572).
After discussion of #572, I added a small bug fix https://github.com/saitoha/mintty-sixel/commit/f93d17f3b3026a197cac40593605c78be091fa55. This PR includes it.
Thanks for a lot of review by @mintty.

### CODE REVIEW

**Comment by mintty** [comment]
The rendered Sixel image is spoiled after changing to/from the alternate screen (e.g. using less or an editor). Sorry I didn't notice it before, it was already the case with the previous version but not with the version of 2nd Aug.

**Comment by mintty** [comment]
@saitoha: This broke in commit https://github.com/saitoha/mintty-sixel/commit/3910883242bc3e6d0dc8940892e39963b858e391 "Workaround for scrollback = 0 environment" while the commit before it, "TATTR_SIXEL is no longer needed" still worked.

**Comment by mintty** [comment]
... which was only a small change. Reverting it in the current version fixes the behaviour. What was "Workaround for scrollback = 0 environment" meant to achieve?

**Comment by saitoha** [comment]
> What was "Workaround for scrollback = 0 environment" meant to achieve?

If you revert saitoha@3910883 and set 0 to "Scrollback lines" setting, SIXEL scrolling will not work.

out

> The rendered Sixel image is spoiled after changing to/from the alternate screen

Sorry, I haven't noticed that problem. It is caused by wrong management of term.virtuallines. This patch will fix it.
https://github.com/saitoha/mintty-sixel/commit/4d55cdc0743e792258db0928a8be3b08a2bf2e13

**Pull request merged**
