### PR TITLE
Fix window positioning

### LINKED ISSUE #1046: tabber: The height of tabbar is not considered when setting the window size
To reproduce:
1. `mintty -s 80x30 --tabbar`
2. The height of the terminal may become 28 rows. I expect it becomes 30 rows.

### PR DESCRIPTION
**Pull request by k-takata**
This fixes two issues about window positioning.

1. Fix Alt+F2 behaviour when the window is maximised.
   See: https://github.com/mintty/mintty/pull/1045#issuecomment-709704486

   This also changes the behaviour of `CSI 9 ; [0-3] t`.
   1. Maximise the window vertically.
      `echo -e '\e[9;2t'`
   2. Maximise the window.
      `echo -e '\e[9;1t'`
   3. Restore the window.
      `echo -e '\e[9;0t'`

   This didn't restore the original window size before maximised vertically.
   But now the original size is restored.
   (I'm not sure about the behaviour in other terminals, though.)

2. Consider the size of tabbar on startup.
   Close #1046.

### CODE REVIEW

**Comment by mintty** [comment]
Thanks a lot, the Alt+F2 / restore issue seems to be working with the patch. The startup size doesn't.

**Comment by k-takata** [comment]
> The startup size doesn't.

Hmm, it looks to be working on my side.
Could you show the reproducible steps?

**Comment by mintty** [comment]
Well, I seem to have done one of two test cases wrong.
Fresh invocation (e.g. from desktop shortcut) works.
Running `mintty -size ...` from a running terminal session adapts the size to the previous session, whether it's tabbar-enabled or not. But that's likely OK.
So it works, great.
Why is it marked "work in progress" and cannot be merged?

**Comment by k-takata** [comment]
> Running `mintty -size ...` from a running terminal session adapts the size to the previous session, whether it's tabbar-enabled or not. But that's likely OK.

Oh, I forget to consider this case. I think that the size from the command line option should be adapted when tabbar is not enabled. Let me check this.

> Why is it marked "work in progress" and cannot be merged?

Because I was not confident about the change of `CSI 9 ; [0-3] t`.

**Comment by k-takata** [comment]
> I think that the size from the command line option should be adapted when tabbar is not enabled.

It seems it works as expected.

**Comment by mintty** [comment]
CSI 9 works fine for me.
Using `-size`, now you've talked about considering this, let's check this case:
TabBar not enabled in config.
Mintty running without tabbar, size 80x33. Start this:
`../bin/mintty -size 99x11` works fine.
`../bin/mintty -size 99x11 -tabbar` will capture the new terminal size and position over the old one (despite not having a tabbar), size is 88x33.
If you think this glitch is acceptable, we can go with it.

**Comment by k-takata** [comment]
That might be a rare case, but I committed a fix for that.

**Comment by Biswa96** [comment]
In `src/winmain.c`, there is FindWindowEx and FindWindowExA both. FindWindowEx maybe A or W depending on `-DUNICODE`.

**Comment by k-takata** [comment]
That part doesn't use a string, so it's not affected by `-DUNICODE`.
Should I use A or W explicitly?

**Comment by mintty** [comment]
This is an interesting point. I do try to maintain A vs W explicitly so mintty can be compiled with `make CCOPT=-DUNICODE` which I occasionally check. Calls without a string don't need the suffix.
However, in `(LPCTSTR)(uintptr_t)class_atom` there is a string cast involved.
As the atom thing was created with RegisterClassEx**W**, I think it may be safer(*) to use FindWindowExW here,
but then it is also necessary to adapt the cast to either (LP**W**STR) or (LPC**W**STR), dropping the 'T' which is a weird variant anyway; otherwise, mintty will not compile on 32-bit cygwin anymore.

(*) Why could that be safer? I had some very weird and very hard to debug interference when trying to enable Unicode support in the menu tree (left part) of the Options dialog. It was essential to changed something explicitly to 'W' in order to make that work, as commented in windialog.c, without any direct API relation, so that it could not be detected by compilation...

**Comment by k-takata** [comment]
> (*) Why could that be safer? I had some very weird and very hard to debug interference when trying to enable Unicode support in the menu tree (left part) of the Options dialog.

In my understanding, RegisterClass and the message loop should use the W APIs to support Unicode text.
No need to use FindWindowExW if the window title or the class name doesn't include Unicode text.

**Comment by mintty** [comment]
> No need to use FindWindowExW if the window title or the class name doesn't include Unicode text.

Both the title (albeit not appearing in RegisterClassExW) and the class (which does appear there) can have Unicode characters (see option `-o Class` for the latter, which can be used to group multiple tab sets).
I have tested both features work nonetheless, however, I'd just feel slightly more comfortable with the "W" version...

**Comment by k-takata** [comment]
Updated

**Pull request merged**
