### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by irakliy01**
Corrected several mistakes. Also, I've changed some sentences. Now they are more correct.

### CODE REVIEW

**Comment by mintty** [comment]
Thanks.
Do you also have translations for the following new entries?

msgid "Duplicate option '%s'"

(the beep names can also be left untranslated if you think that's better)
msgid "simple beep"
msgid "no beep"
msgid "Default Beep"
msgid "Critical Stop"
msgid "Question"
msgid "Exclamation"
msgid "Asterisk"

**Comment by irakliy01** [comment]
> msgid "Duplicate option '%s'"

Is here the word 'duplicate' a verb or an adjective?

------------------------------------------------

msgid "simple beep"
msgid "no beep"
msgid "Default Beep"
msgid "Critical Stop"
msgid "Question"
msgid "Exclamation"
msgid "Asterisk"

msgid "simple beep"
msgid "no beep"
msgid "Default Beep"
msgid "Критическая остановка"
msgid "Вопрос"
msgid "Восклицание"
msgid "Звездочка (*)"

**Comment by mintty** [comment]
It's an adjective.

**Comment by irakliy01** [comment]
msgid "Duplicate option '%s'"

msgid "Дублированный вариант '%s'"

**Comment by mintty** [comment]
Thank you.

**Pull request merged**
