### PR TITLE
Add support for windows 10

### PR DESCRIPTION
**Pull request by march1993**
Including the support for `SetWindowCompositionAttribute` function to enable blur behind the window.
Problem: it would become effective only after rebooting.

### CODE REVIEW

**Comment by mintty** [comment]
Thanks for your contribution. Compare to #501 with a similar patch.
However, I cannot currently reproduce the effect. Activating "glass" makes the background plain white here. I am aware that there used to be some Windows configuration conditions for glass mode (see manual page) but cannot replay that configuration either in a current Windows 10 version.
If you can provide more insights, especially a reproducible test case to actually make the effect visible, that would help to assess the patch.
(And by the way, I would prefer patches not to strip all line-ending spaces from the file, just to enhance overview...)

**Comment by march1993** [comment]
I'm running with Windows 10 1703. It works somehow.

qq 20170517232720

Though many problems still remain. For example, text drawn by GDI doesn't have alpha channel.
I tried years ago to replace all TextOut with DrawThemeTextEx. But it's quite slow.
Another way is to use gdiplus, which brings even more problems :p

**Comment by mintty** [comment]
Let me repeat more clearly: I do not see any difference by your patch. Everything looks like without the patch. If there is a difference in certain configuration cases, please provide details.

**Comment by mintty** [comment]
@march1993 (and  @jdmansour):
It seems I have accidentally checked in this patch so it's now included in th 2.7.7 release, without mention in the changelog. Sorry for overlooking this. I will consider to leave it in as long as nobody complains.

And I will of course add credits for both of you (with similar contributions) in the commit history and on the credits wiki page provided that I can see a reproducible benefit of this in my environment. As said before, I don't see any difference now, so some setup instructions may help... I don't know whether this may be related to the hint in the mintty manual page, under the Transparency/Glass option. I also don't find this Windows setting anymore in Windows 10...

**Comment by jdmansour** [comment]
Hi, cool, I'll try it out when I have some time. I don't remember if calling SetWindowCompositionAttribute was enough, though. It might work and you'll get everything transparent, including text (like right now when you choose e.g. 75% regular transparency), but in could also do nothing if the window has no alpha channel. @march1993, does the patch work for you?

One future improvement would be to add per-pixel-alpha, as in my fork. This way, text is 100% opaque, while the background is partially transparent and blurred. The way I implemented it is very messy and inefficient though. When I have some more time, I'll think about a better way.

Another improvement is that Microsoft has now announced "Fluent Design", which includes an official "Acrylic" blur effect. Unfortunately, this is only available in WPF apps. However, I think I've found out how it is implemented (as DirectComposition filters), and there has got to be a secret API to tell the windows DWM to apply a certain filter to a window. This is going to be a real challenge :-) but I think if it is possible, we will be able to just drop it in.

**Comment by Guerra24** [comment]
Hi, the patch "works", not as expected but it does. The main issue is that blurs the entire window, including the window frame, and the text transparency is broken. For it to work: change to glass, save, close and open.

img

**Comment by mintty** [comment]
Is that really how you want it to look? With also the text blurred (kind of, looking at the coloured-background lines)? And does the border look different after Save? For me it doesn't.

**Comment by mintty** [comment]
Anyway, the way it looks in your screenshot is the same as it looked already before the patch (with -o Transparency=Glass).

**Comment by Yamakuzure** [comment]
Well, for me it looks like the following screenshot on Windows 10 Pro. The screenshot is from today.

mintty_glass_01

(At least there is a glassy edge around the window, where the shadow should've been...)

Unfortunately I have no idea how to fix this.

**Pull request closed without merging**
