### PR TITLE
Update fr.po

### PR DESCRIPTION
**Pull request by Gozer-404**
Did a global review of the complete file today

### CODE REVIEW

**Comment by Gozer-404** [comment]
Sorry closed by mistake

**Comment by mintty** [comment]
Thanks. Note that it is not necessary to add identical transforms (e.g. msgid "xterm" msgstr "xterm") as an empty msgstr will just default to the msgid.
Also, about the extended Sup->Super, Hyp->Hyper, please check whether they do not overflow their space in the Options menu, section Window.

**Comment by Gozer-404** [comment]
Just a small comment on your note, I did the copy of the same strings "on purpose" because I often use poedit which, by default, puts all the empty strings on the top... By doing this I can see the (new) untranslated strings easily ;=)

**Comment by mintty** [comment]
Bien. Look at my other comment and how Super and Hyper are squeezed into the menu:
grafik
That's why I'd suggest to keep them abbreviated.

**Comment by Gozer-404** [comment]
You're right... I didn't get the comment (because I didn't test my changes, sorry).
Lets keep these two abbreviated... but could it be possible to have the keys/checkboxes on two rows instead of one ? or a wider dialog window ?

**Comment by mintty** [comment]
Closing this PR in favour of the new one.
Two lines don't fit. You could make the Options window wider per localization using pseuro-iteim `msgid "100"` (see https://github.com/mintty/mintty/wiki/Tips#adding-translations-to-localization), although that's mainly intended for CJK locales (but also used for Hungarian).

**Comment by BrianInglis** [comment]
Why not just expand the space for menu and dialogue text to accommodate double width characters so there is also more space for localization translations? 
Then you could remove the scaling code and reduce complexity.

**Comment by mintty** [comment]
I think the scaling option makes sense as there are languages that take up more space than others.

**Pull request closed without merging**
