### PR TITLE
improve search performance. (revised)

### PR DESCRIPTION
**Pull request by account-login**
https://github.com/mintty/mintty/pull/986 resubmitted.

### CODE REVIEW

**Comment by mintty** [comment]
Is this your search-3-pr branch? Asking for easier testing, as I need to fiddle this out against current work I'm doing on the same files, unfortunately.
Also I forgot to ask: does the __asm__ inline have significant advantage over C-based time retrieval? (See e.g. function mtime which is already available.)

**Comment by BrianInglis** [comment]
Advantage of `rdtsc` over `mtime()` is low overhead returning approximate clock cycle counts +/- pipeline and speculation effects. 
For accuracy `rdtscp` should give more repeatable results with less uncertainty. 
If significant improvements are made, `mtime()` overhead is higher, but should be adequate to show differences: if time differences appear minimal, improvement is likely minimal. 

If rdtsc is required, it would be better to use `#include <intrin.h>` or `#include <ia32intrin.h>` with `__rdtsc()` `_rdtsc()` `_rdtscp()` macros, to invoke compiler and architecture builtins, avoid issues, and get compiler warnings if there are issues, across both 32 and 64 bit builds; see output from e.g.:
`$ fgrep rdtsc /{usr,lib/gcc/*86*/*}/include/**/*intrin.h`

**Also:**
It would be better if the initial patch avoided deleting complete functions, as it makes it less clear what is being changed and improved. 
A separate patch in the same series can clean up unused functions later (if required).

**Comment by mintty** [comment]
Released 3.1.5.

**Comment by kiwiz** [comment]
Thanks for pinging me. If I recall correctly, the search code is executed on every window update to handle the case where a window resize reflows text. Not sure if that is still a consideration from a quick read of the code.

**Comment by mintty** [comment]
Thanks for the check.
@account-login, can you please check this case. If it is a problem, we might add an update when the terminal is actually getting resized.

**Comment by account-login** [comment]
Thanks for the check. I've verified that the window resizing triggers search update as before, since the condition for search update is not changed.

**Comment by kiwiz** [comment]
I went back to see why I implemented it this way and found this comment: https://github.com/mintty/mintty/issues/85#issuecomment-292057196

I don't fully understand what `result.idx` represents, but does the new approach obviate the requirement of refreshing results on every update?

**Comment by mintty** [comment]
I do not fully understand either the previous or the current strategy, sorry; so checking some remarks of your referenced comment, I just checked Insert/Delete Line/Char which apparently works, so I have the impression we can go on with the current strategy...

**Comment by kiwiz** [comment]
Sounds good, thanks all!

**Pull request merged**
