### PR TITLE
Update german de.po, release Croatian hr.po

### PR DESCRIPTION
**Pull request by milotype**
Both translations are complete

### CODE REVIEW

**Comment by mintty** [comment]
Thanks for the contribution.
The German translation is actually from myself and I'd like to check changed proposals in detail. Particularly, you are suggesting to make some labels longer, which would then become too long and get clipped in the Options menu, e.g. "Schriftgrad" and "Teilweise".
Please separate the two files and submit the Croation translation in a distinct PR for now.

**Comment by milotype** [comment]
I'm sorry to cause trouble :-(
Unfortunately you did not specify the length of strings. If it's essential, I'd propose you specify it (for instance as a comment in the .po/.pot file).
Until then, please let me know the length of those strings, so I can make appropriate changes in Croatian, if necessary.
Are you going to change the German translation?

**Comment by milotype** [comment]
P.S.
Ideally, windows, pop-ups or other visuals should expand to the necessary sizes, so text doesn't get cut off, independent of the locale/language (unfortunalely, I'm not a programer, so I don't know how to solve such issues) :-((

**Comment by mintty** [comment]
Length of strings could only be specified in pixels, not characters, so that's a problem.
With your translation, you should walk through the options dialog completely and carefully to detect any trouble. Open colours and font menus also, try `mintty -o FontMenu=0` for a variant.
Your suggestion is good in theory, but a nightmare at the Windows API. If the dialog is too small, you can expand it with a pseudo-translation of `msgid "100"`.

**Comment by milotype** [comment]
As said before, I'm just a translator who's helping to localize apps ... I don't actually use mintty and I'm not a programer ... Can you please specify the length of strings which seem to be problamatic?

**Comment by mintty** [comment]
Oh, I see. The following strings appear too long. I've clipped them approximately as they appear.

msgid "&Off"
msgstr "&Isključeno"
msgstr "&Iskljui"

msgid "&Sat:"
msgstr "Za&sićenost:"
msgstr "Za&sićenos:"

msgid "&Lum:"
msgstr "&Osvjetljenost:"
msgstr "&Osvjetljeno:"

msgid "&Partial"
msgstr "&Djelomično"
msgstr "&Djelomič"

msgid "&Default"
msgstr "&Standardno"
msgstr "&Standari"

msgid "&Full"
msgstr "&Potpuno"
msgstr "&Potpuni"

msgid "&Menu and Full Screen (Alt+Space/Enter)"
msgstr "&Izbornik i cjeloekranski prikaz (Alt+razmaknica/Enter)"
msgstr "&Izbornik i cjeloekranski prikaz (Alt+razmaknica"

msgid "Clic&ks place command line cursor"
msgstr "&Pritiskanje miša postavlja kursor u naredbenom retku"
msgstr "&Pritiskanje miša postavlja kursor u naredbenon"

msgid "Show size while selecting (0..12)"
msgstr "Prikaži veličinu tijekom označavanja (0 … 12)"
msgstr "Prikaži veličinu tijekom označavanja"

msgid "C&urrent size"
msgstr "Trenutačna veličina"
msgstr "inutačna velič"

msgid "&Flash"
msgstr "&Zabljesni"
msgstr "&Zabljesr"

msgid "&Highlight in taskbar"
msgstr "&Istakni u programskoj traci"
msgstr "&Istakni u programs"

msgid "&Popup"
msgstr "&Skočni prozor"
msgstr "&Skočni pro"

**Comment by milotype** [comment]
This is the best I can do ... but it's realy *bad* … pixel-based sizes are definetely problematic when localizing …

msgid "&Off"
msgstr "&Isklj."

msgid "&Sat:"
msgstr "Za&sić.:"

msgid "&Lum:"
msgstr "&Osvjet.:"

msgid "&Partial"
+msgstr "&Djelomič"

msgid "&Default"
msgstr "&Standard"

msgid "&Full"
msgstr "&Potpuno"

msgid "&Menu and Full Screen (Alt+Space/Enter)"
msgstr "&Izbornik i ekran (Alt+razmak/Enter)"

msgid "Clic&ks place command line cursor"
msgstr "&Pritisak postavlja pokazivač"

msgid "Show size while selecting (0..12)"
msgstr "Veličina označavanja  (0 … 12)"

msgid "C&urrent size"
msgstr "Veličina"

msgid "&Flash"
msgstr "&Bljesak"

msgid "&Highlight in taskbar"
msgstr "&Istakni u traci"

msgid "&Popup"
msgstr "&Skočni"

**Comment by mintty** [comment]
You could also expand the menu by setting
msgid "100"
msgstr "130"
and go with your original translations, except two in the Colours popup:
grafik

**Comment by milotype** [comment]
Ahhh ... now I understand the comment in that string.
But are you saying, that no matter what higher value I put there, only the two strings `&Sat:` and `&Lum:` will not benefit from it, and that they need to be abbreviate?

**Comment by mintty** [comment]
Tried again; apparently, those labels do in fact not benefit from the spreading, not sure why.

**Comment by milotype** [comment]
Thanks. So, would the following be OK for the Croatian:

- I'll change the value to 140 (just to be on the safe side)
- I'll abbreviate only the two strings for `&Sat:` and `&Lum:`

**Comment by mintty** [comment]
130 looks fine. 140 looks too wide, really.
And you can use 2 more letters or 4 more letters, respectively, if that helps, as I suggested:

msgid "&Off"
msgstr "&Isključeno"
msgstr "&Iskljui"

msgid "&Sat:"
msgstr "Za&sićenost:"
msgstr "Za&sićenos:"

**Comment by mintty** [comment]
Closed via #992.

**Pull request closed without merging**
