### PR TITLE
dim: simplify, improve, decouple from BoldAsColour

### PR DESCRIPTION
**Pull request by avih**
Quite simple, really...

### CODE REVIEW

**Comment by avih** [comment]
Oh, actually, this also needs docs changes. Please wait with the merge.

**Comment by avih** [comment]
> this also needs docs changes

Added docs, rebased, and force-pushed.

**Comment by mintty** [comment]
I can do the docs, too, as you like.
However, this one actually withdraws some options. Especially, as I'd prefer to blend with current background, the removal of function truecolour may be premature.

**Comment by avih** [comment]
> I'd prefer to blend with current background

This part of the commit message explains why it's a bug:
```
- Blend with the cell background only sort of works with non coloured
  background (gray/black/white). With coloured background the fg colour
  changes in an unexpected way for "dim".
```

And this bug currently (i.e. before the fix) already happens on all those cases (also at from the commit message):
```
If BoldAsColour=no and/or it's the default colour and/or it's a true colour:
- blend the fg with the cell's bg.
```

Let's have xterm as some reference:
Xterm default config: left side: top: normal, bottom: reverse (7). Right side: same as the left-side but also with dim (2).
xterm-all-combos

Now let's look at mintty with default configuration (so BoldAsColour=yes):
Left side: normal/reverse. Middle: with dim - with mintty before the PR. Right-side: with dim after this PR:
mintty-dim-fix-yes-colour

At the middle terminal (mintty before the dim change), and in it at the bottom output (for `sgrtab -g 7 2`). See how the first two lines look weirdly out of place? That's the default colour with and without bold - that's the bug.

Now compare it to the xterm dim at the right-side of the top screenshot.

The bug is also always affecting (not seen at the screenshots) true colours, And when BoldAsColour=no then it affects all colours.

For instance, the same three terminals with default everything except BoldAsColour=no:
mintty-dim-fix-no-colour

So now this weird behavior extended to everything.

It's a bug. It's exactly one of the bugs which this PR fixes.

**Comment by avih** [comment]
> this one actually withdraws some options

For the record, if you look at the history of dim at the commit message, it becomes pretty clear it was never about a configuration option, it was a way to make dim "smarter" by taking more factors into account. And it only wanted to get smarter because it got it wrong in the first place.

It didn't end up very smart, certainly not after all the changes it went through, and the association between BoldAsColour and dim has always been a weird one to say the least, and eventually it "chooses" between one set of bugs to another set of bugs. Instead of just make it stupid and working and without being unnecessarily smart.

**Pull request merged**
