### PR TITLE
Unuseful variable in winsearch.c (searched).

### PR DESCRIPTION
**Pull request by paolo-sz**
It also introduces a delay on the first "next result" button push

### CODE REVIEW

**Comment by mintty** [comment]
What delay? Please explain.
This affects code by @kiwiz (#85), so I'd like to give him opportunity to comment.

**Comment by paolo-sz** [comment]
Just try to do the following:
- open the search bar
- write a single letter in the edit box in order to have multiple match on the screen (you will now see all the letters you typed highlighted and the first one highlighted as the first match)
- now push the right arrow on the search bar (the first match higilight should be supposed to move to the second match but this does not happens. only starting from the second push you can see the highlight to move...
This is the delay I'm talking about.

**Comment by paolo-sz** [comment]
This better (my point of view) address the case which was managed by the searched variable (first match outside the current visible area).
Also, I feel the serch result it should be cleared if the search bar is cleared as well...

**Comment by paolo-sz** [comment]
Or, even better, just scroll if current match is not visible otherwise change match and scroll (if necessary)

**Comment by kiwiz** [comment]
@paolo-sz I feel like I had a reason for keeping the previous search if the search bar was cleared, but I don't remember why that was. Nonetheless, this change looks good to me!

**Comment by paolo-sz** [comment]
@kiwiz First of all, I was wrong when I said that variable was not useful, sorry.
I think we fall into the same mistake by considering only one scenario of the two (maybe others) possible. This is the reason of my third commit.
About the previous search clears together with search bar, sorry, I'm not able to figure out when it could be useful too...

**Comment by mintty** [comment]
I had the impression from comments above that patch/commit 3 replaces (part of?) patch 2. Not sure whether applying the merge would register all commits which is kind of confusing. Can we have a consolidated patch please? (And there seems to be an indentation quirk in line 29.)

**Comment by paolo-sz** [comment]
Done (with indentation fix also).

**Pull request merged**
