### PR TITLE
docs: Escape hyphens

### LINKED ISSUE #1250: `-` is shown as U+2010 in the manpage
Recently, `man mintty` shows `-` (U+002D, HYPHEN-MINUS) as `‐` (U+2010, HYPHEN).
So, searching for any options on the manpage (using the `/` command) doesn't work. (E.g. `/--WSL`)

E.g.:
https://github.com/mintty/mintty/blob/91bb8cad25f3856bc46f55d60142768a7cceac3f/docs/mintty.1#L36
`-` in this line should be escaped by `\` as follows:
```
implies a \fB\-\-WSL\fP\fI[=distro]\fP parameter.
```

### PR DESCRIPTION
**Pull request by k-takata**
Close #1250

### CODE REVIEW

**Comment by mintty** [comment]
I see your patch carefully distinguishes and preserves in-text hyphens. I'm curious: did you check them all manually or is there a suitable tool? (If there is, I'd prefer to keep the unmodified source and add a transformation to the build to prepare the actual manpage.)

**Comment by k-takata** [comment]
Unfortunately, I couldn't find such a tool. So, I did them manually.

Heuristically, if a `-` is sandwiched in the middle of alphabet characters, it is a hyphen. Otherwise, it is an ASCII hyphen-minus. But there are some exceptions.

**Comment by mintty** [comment]
Thank you very much.

**Comment by BrianInglis** [comment]
See [`groff` doc `PROBLEMS`](https://git.savannah.gnu.org/cgit/groff.git/tree/PROBLEMS) for user `man.local` and `mdoc.local` fixes
*NOTE* that changing the default may result in long option names breaking before or within the name, and/or eliminate hyphenation elsewhere. 
Those outcomes may be acceptable if you are content with ragged right margins, and possibly short lines, especially in translations to agglutinative languages such as Deutsch/German or Suomi/Finnish. 
This file and licences are not yet included in Cygwin groff package: I will request they be included.

**Comment by mintty** [comment]
Or the mintty man page could simply add
`.char - \-`
for a general fix. But now there's the distinct modification already, for code-like dashes only. I only hope to keep the discipline to make that distinction.

**Pull request merged**
